<?php
define('ROOT_RESOURCES_PATH', ROOT_PATH . '/resources');
define('ROOT_RESOURCES_I18N', ROOT_RESOURCES_PATH . '/i18n');
define('ROOT_PHP_PATH', ROOT_PATH . '/src/php');
define('ROOT_COMPONENTS_PATH', ROOT_PATH . '/components');
define('ROOT_COMPONENTS_TEMPLATES_PATH', ROOT_COMPONENTS_PATH . '/templates');
define('ROOT_COMPONENTS_TOOLS_PATH', ROOT_COMPONENTS_PATH . '/tools');
define('ROOT_COMPONENTS_UI_PATH', ROOT_COMPONENTS_PATH . '/ui');
define('ROOT_COMPONENTS_MODALS_PATH', ROOT_COMPONENTS_PATH . '/modals');
?>